---

num_rounds: 2
num_clients: 2
batch_size: 20
num_classes: 2
# r: [6,6,7,7,8]
r: [7,8]
# r: 8
hetero: True
num_clients_per_round_fit: 2
num_clients_per_round_eval: 2
checkpoint: "distilbert-base-uncased"
config_fit:
  lr: 0.001
  momentum: 0.9
  local_epochs: 1