---

num_rounds: 5
num_clients: 3
batch_size: 20
num_classes: 2
# r: [6,6,7,7,8]
r: [6,7,8]
# r: 8
hetero: True
padding_strategy: "linear"
num_clients_per_round_fit: 3
num_clients_per_round_eval: 3
checkpoint: "distilbert-base-uncased"
config_fit:
  lr: 0.001
  momentum: 0.9
  local_epochs: 1